/home/jc/Documentos/felizometro2.sql
/home/jc/Documentos/juanca/sivicj/bd/sivicj_09dic2013_175501.sql
/home/jc/Documentos/juanca/sivicj/bd/sivicj_06dic2013_175501.sql
/home/jc/Documentos/juanca/sivicj/bd/sivicj_10dic2013_175501.sql
/home/jc/Documentos/juanca/sivicj/protected/extensions/eyui/eyuiformeditordb-sqlite-schema.sql
/home/jc/Documentos/juanca/sivicj/protected/extensions/eyui/eyuiformdb-mysql-schema.sql
/home/jc/Documentos/juanca/sivicj/protected/extensions/eyui/eyuiformeditordb-mysql-schema.sql
/home/jc/Documentos/juanca/sivicj/protected/extensions/eyui/eyuiformdb-sqlite-schema.sql
/home/jc/Documentos/juanca/sivicj/protected/extensions/ireport/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/sivicj/protected/extensions/ireport/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/sivicj/protected/extensions/phpjasper/phpjasperxml/sampledb.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/cruge1/data/cruge-data-model-postgres.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/cruge1/data/cruge-data-model.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/yii-user-management-master/user/docs/yum_translation.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/yii-user-management-master/user/docs/fresh_installation.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/cruge/data/cruge-data-model-postgres.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/cruge/data/cruge-data-model.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/cruge3/data/cruge-data-model-postgres.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/cruge3/data/cruge-data-model.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/user/docs/yum_translation.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/user/docs/fresh_installation.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/cruge2/data/cruge-data-model-postgres.sql
/home/jc/Documentos/juanca/sivicj/protected/modules/cruge2/data/cruge-data-model.sql
/home/jc/Documentos/juanca/sivicj/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/sivicj/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/sistemainformacion.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/todo.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/tabulados_20141/protected/modules/rights/data/schema.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/tabulados_20141/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/tabulados_20141/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/tabulados_20141/BD/tabulados.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/promigas/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/promigas/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/adminincampo/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/adminincampo/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/plugins/system/rokcommon/sql/install.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/plugins/system/rokcommon/sql/uninstall.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_contact/sql/install.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_contact/sql/uninstall.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_weblinks/sql/install.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_weblinks/sql/uninstall.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_banners/sql/install.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_banners/sql/uninstall.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_finder/sql/install.postgresql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_finder/sql/uninstall.postgresql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_finder/sql/uninstall.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_finder/sql/install.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.1-2012-01-26.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.1-2011-09-15-2.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.10.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.4-2011-12-12.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.1-2011-09-15.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.4-2011-11-23.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.7.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2012-01-14.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.1-2011-09-17.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2011-12-20.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.3-2011-11-10.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.0-2011-06-06.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.16.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.3-2011-10-19.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.13.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2011-12-19.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2011-12-21-1.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.4-2011-11-19.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2011-12-24.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.1-2011-09-20.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.2-2012-03-05.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.19.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2011-12-22.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.12.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2011-12-06.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2012-01-10.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.3-2011-10-15.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.4-2012-03-18.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.9.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.5.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.18.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.4-2012-03-19.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2011-12-23.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.11.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.14.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.6.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2011-12-16.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.0-2011-12-21-2.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.1-2011-09-15-4.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.3-2012-03-13.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.1-2011-09-15-3.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.17.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/2.5.15.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.0-2011-06-06-2.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/mysql/1.7.0.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.10.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.7.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.16.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.13.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.2-2012-03-05.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.19.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.12.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.4-2012-03-18.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.9.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.5.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.18.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.4-2012-03-19.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.11.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.14.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.6.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.3-2012-03-13.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.17.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_admin/sql/updates/sqlazure/2.5.15.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_aicontactsafe/uninstall.aicontactsafe.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_aicontactsafe/install.aicontactsafe.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_attachments/sql/updates/mysql/3.1.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_attachments/sql/updates/mysql/3.1-2012-11-17.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_attachments/sql/updates/mysql/3.0.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_attachments/sql/updates/mysql/3.1-2013-04-29.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_attachments/sql/uninstall.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_attachments/sql/install.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_rokgallery/install/install.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_rokgallery/install/uninstall.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_newsfeeds/sql/install.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_newsfeeds/sql/uninstall.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_roksprocket/install/install.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_roksprocket/install/uninstall.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_rokcandy/sql/install.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_rokcandy/sql/sampledata.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cncV2/administrator/components/com_rokcandy/sql/uninstall.mysql.utf8.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/egm2013/contactos2010b.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/egm2013/egm.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/mansarovar/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/mansarovar/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/tabulados_2014/protected/modules/rights/data/schema.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/tabulados_2014/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/tabulados_2014/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/tabulados_2014/BD/tabulados.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/protected/modules/rights/data/schema.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/encues2_catimonitoreo.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/encuestador_reporteUno.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/consultas1.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/user_authassigment.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/supervisor_reporteUno2.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/views.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/yiincampo.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/supervisor_informe_encuestador.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/reporteUno_encuestadores.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/views/user_authassigment.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/views/reporteUno_supervisores.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/views/supervisor_informe_encuestador.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/views/reporteUno_encuestadores.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiincampo/BD/supervisor_reporteUno.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/phpMyAdmin/examples/create_tables.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/phpMyAdmin/examples/create_tables_drizzle.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/phpMyAdmin/examples/upgrade_tables_mysql_4_1_2+.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/tecnomae_cnc14.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/sql_formularios.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/formularios/dfa_bancas_y_companias/sql_actions.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/formularios/dgs/nuevos_formularios_13_11_2013/sql_actions.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/formularios/dsf_externo_fuerzas_militares/formularios_13_11_2013/sql_actions.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/cargue inicial.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/truncate_respuestas.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/encues2_ecopetrol2013 (remoto).sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/db_alex.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/migrations.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/db.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/cambios felipe correccion martha.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/updates alejo.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/Script_ecopetrol_configuracion.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/Script_ecopetrol_configuracion_completo.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/cambios final.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/base.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/tablas formularios felipe.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/config_formulario.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/form_generator/db/script truncar config_formulario y volver a subir.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/carnetscnc/protected/data/encues2_carnetscnc_data.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/carnetscnc/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/carnetscnc/protected/data/schema.inicial.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/carnetscnc/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/carnetscnc/protected/data/encues2_carnetscnc.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/carnetscnc/protected/data/encues2_carnetscnc_postgresql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/moodle/lib/dml/oci_native_moodle_package.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/framework/web/auth/schema-pgsql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/framework/web/auth/schema-mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/framework/web/auth/schema-sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/framework/web/auth/schema-mssql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/framework/web/auth/schema-oci.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/framework/cli/views/webapp/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/framework/cli/views/webapp/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/installer/sql/create-pgsql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/installer/sql/create-mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/limesurvey/installer/sql/create-mssql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cnccol/protected/extensions/yiistrap/tests/_data/dump.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cnccol/protected/modules/rights/data/auth_schema.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cnccol/protected/modules/rights/data/rights-insert-sqlserver.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cnccol/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/cnccol/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/protected/modules/rights/data/schema.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/gestion/BD/backup.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/temp.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/insert/27-Febrero-2014/insert_contacto_empresa_nuevos1.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/insert/27-Febrero-2014/insert_encuesta_contacto_nuevos1.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/insert/27-Febrero-2014/insert_contacto_medio_comunicacion_nuevos1.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/reporte_consolidado_gestion.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/anuladas/anuladas_trigos.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/parafinas_informe_campo_consolidado.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/reporte_consolidado_gestion_parafinas.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/historial_interacciones.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/contactos_efectivos_no_marcador.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/parafinas_empresas_efectivas.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/views/historial_interaccion.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/backup_encues2_ecp_tracking_gestion_2014.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/ecp_tracking_2014/BD/parafinas_efectivos_con_gestion.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiismo/protected/modules/rights/data/schema.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiismo/protected/data/schema.yiismo.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yiismo/protected/data/encues2_yiismo.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/webcnc/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/webcnc/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/comfandi/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/comfandi/protected/data/schema.inicial.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/comfandi/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/saludpublica/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/saludpublica/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/egm2014/contactos2010b.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/egm2014/backup/idm_2013Ola3.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/egm2014/egm.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra1/protected/data/pgplsql_basemaestra.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra1/db/basemaestra.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra1/db/basemaestra2.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra1/db/basemaestra3.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/sistemainformacion/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/sistemainformacion/protected/data/schema.inicial.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/sistemainformacion/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/sistemainformacion/protected/data/schema.mysql_inicial.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/framework/web/auth/schema-pgsql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/framework/web/auth/schema-mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/framework/web/auth/schema-sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/framework/web/auth/schema-mssql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/framework/web/auth/schema-oci.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/framework/cli/views/webapp/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/framework/cli/views/webapp/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/demos/phonebook/protected/data/schema.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/demos/blog/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/yii/demos/blog/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/mansarovar2/db/script.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/default/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/default/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/demo1/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/demo1/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/base/protected/data/schema.base.postgres.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra2/protected/data/pgplsql_basemaestra.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra2/db/basemaestra.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra/protected/data/pgplsql_basemaestra.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra/db/basemaestra.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra/db/basemaestra2.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/basemaestra/db/basemaestra3.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/incampo/sql/encues2_catimonitoreo.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/estudioscnc/protected/modules/rights/data/schema.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/estudioscnc/protected/data/schema.mysql.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/estudioscnc/protected/data/schema.sqlite.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/estudioscnc/BD/encues2_yiistarter.sql
/home/jc/Documentos/juanca/pc/media/jean/cuidado/www/estudioscnc/BD/views.sql
/home/jc/Documentos/p.sql
/home/jc/Documentos/backup/sistemainformacion.sql
/home/jc/Documentos/backup/encues2_ecaradio.sql
/home/jc/Documentos/backup/encues2_sistemareporte-201407170231.sql
/home/jc/Documentos/backup/catimonitoreo_10-07-2014.sql
/home/jc/Documentos/backup/encues2_ecaradio_new.sql
/home/jc/Documentos/backup/encues2_egm.sql
/home/jc/Documentos/backup/encues2_ECAR.sql
/home/jc/Documentos/backup/encues2_ESTUDIOS.sql
/home/jc/Documentos/backup/sistemainformacion_07_01_2014.sql
/home/jc/Documentos/backup/encues2_ESTUDIOS_bkp.sql
/home/jc/Documentos/backup/encues2_invescuali.sql
/home/jc/Documentos/backup/encues2_cncdb3.sql
/home/jc/Documentos/backup/encues2_ecampo.sql
/home/jc/Documentos/backup/carnetscnc.sql
/home/jc/Documentos/backup/encues2_SURCNC.sql
/home/jc/Documentos/backup/encues2_Lime.sql
/home/jc/Documentos/backup/encues2_cncdb2.sql
/home/jc/Documentos/backup/encues2_cncdb (1).sql
/home/jc/Documentos/backup/encues2_framework.sql
/home/jc/Documentos/backup/encues2_project_db.sql
/home/jc/Documentos/backup/encues2_prueba2.sql
/home/jc/Documentos/backup/encues2_dbwebcnc.sql
/home/jc/Documentos/backup/view_regcluster2_2014_ola1.sql
/home/jc/Documentos/backup/view_regcluster2_2014_ola1-1.sql
/home/jc/Documentos/backup/encues2_ESTUDIOS_2014_06_12.sql
/home/jc/Documentos/backup/encues2_comfandi.sql
/home/jc/Documentos/backup/encues2_phplistdb.sql
/home/jc/Documentos/backup/catimonitoreo_26-06-2014.sql
/home/jc/Documentos/backup/catimonitoreo_19-06-2014.sql
/home/jc/Documentos/backup/encues2_cncdb.sql
/home/jc/Documentos/felizometro3.sql
/home/jc/Documentos/estructuracncdb-respuestasegm14_ola1.sql
/home/jc/Documentos/sistemainformacion/protected/data/schema.mysql.sql
/home/jc/Documentos/sistemainformacion/protected/data/schema.inicial.sql
/home/jc/Documentos/sistemainformacion/protected/data/schema.sqlite.sql
/home/jc/Documentos/sistemainformacion/protected/data/schema.mysql_inicial.sql
/home/jc/Documentos/estructuracncdb-registros_culster2014_ola1.sql
/home/jc/Documentos/felizometro.sql
/home/jc/Documentos/encues2_cncdb.sql
/home/jc/todo.sql
/home/jc/lampp/share/mysql/mysql-test/lib/init_db.sql
/home/jc/lampp/share/mysql/mysql-test/t/mysql_delimiter.sql
/home/jc/lampp/share/mysql/mysql-test/t/mysql_delimiter_19799.sql
/home/jc/lampp/share/mysql/mysql-test/t/mysql_delimiter_source.sql
/home/jc/lampp/share/mysql/fill_help_tables.sql
/home/jc/lampp/share/mysql/mysql_fix_privilege_tables.sql
/home/jc/lampp/phpsqliteadmin/create_system_db.sql
/home/jc/lampp/lib/php/doc/HTML_Template_Xipe/docs/translate.mysql.sql
/home/jc/lampp/lib/php/doc/DB_QueryTool/docs/examples/mysql.sql
/home/jc/lampp/lib/php/doc/DB_QueryTool/docs/examples/pgsql.sql
/home/jc/lampp/lib/php/doc/XML_sql2xml/doc/xmltest.sql
/home/jc/lampp/lib/php/doc/DB_NestedSet/docs/testdb_mysql.sql
/home/jc/lampp/lib/php/doc/DB_NestedSet/docs/mysql.sql
/home/jc/lampp/lib/php/doc/Tree/docs/TreeEditor/mysql_db.sql
/home/jc/lampp/lib/php/doc/Tree/docs/Dynamic_DBnested.sql
/home/jc/lampp/lib/php/doc/Mail_Queue/docs/mysql.sql
/home/jc/lampp/lib/php/doc/Mail_Queue/docs/pgsql.sql
/home/jc/lampp/lib/php/doc/MDB_QueryTool/docs/examples/mysql.sql
/home/jc/lampp/lib/php/doc/MDB_QueryTool/docs/examples/pgsql.sql
/home/jc/lampp/lib/php/test/Auth_HTTP/tests/sample.sql
/home/jc/lampp/lib/php/data/Log/misc/log.sql
/home/jc/lampp/phpmyadmin/scripts/create_tables_mysql_4_1_2+.sql
/home/jc/lampp/phpmyadmin/scripts/create_tables.sql
/home/jc/lampp/phpmyadmin/scripts/upgrade_tables_mysql_4_1_2+.sql
/home/jc/lampp/htdocs/carvajal/carvajal2010/backups/BaseProfesores.sql
/home/jc/lampp/htdocs/carvajal/carvajal2010/backups/SQL.sql
/home/jc/lampp/htdocs/carvajal/carvajal2010/cnc.sql
/home/jc/lampp/htdocs/carvajal/carvajal2010/carv_rta_2010.sql
/home/jc/lampp/htdocs/carvajal/gestion/informe/tabla_pregunta_informe.sql
/home/jc/lampp/htdocs/carvajal/gestion/informe/SQL_informe.sql
/home/jc/lampp/htdocs/carvajal/gestion/informe/carvajal_gestion_rta.sql
/home/jc/.dbeaver/General/Scripts/Script-16.sql
/home/jc/.dbeaver/General/Scripts/Script-4.sql
/home/jc/.dbeaver/General/Scripts/Script-1.sql
/home/jc/.dbeaver/General/Scripts/Script-2.sql
/home/jc/.dbeaver/General/Scripts/Script-7.sql
/home/jc/.dbeaver/General/Scripts/Script-13.sql
/home/jc/.dbeaver/General/Scripts/Script-5.sql
/home/jc/.dbeaver/General/Scripts/Script-9.sql
/home/jc/.dbeaver/General/Scripts/Script-10.sql
/home/jc/.dbeaver/General/Scripts/Script-11.sql
/home/jc/.dbeaver/General/Scripts/Script-12.sql
/home/jc/.dbeaver/General/Scripts/Script.sql
/home/jc/.dbeaver/General/Scripts/Script-6.sql
/home/jc/.dbeaver/General/Scripts/Script-3.sql
/home/jc/.dbeaver/General/Scripts/Script-8.sql
/home/jc/.dbeaver/General/Scripts/Script-15.sql
/home/jc/.dbeaver/General/Scripts/Script-14.sql
/home/jc/openkm-6.3.0-community/tomcat/webapps/OpenKM/WEB-INF/classes/extensions/automation.sql
/home/jc/openkm-6.3.0-community/tomcat/webapps/OpenKM/WEB-INF/classes/extensions/extensions.sql
/home/jc/openkm-6.3.0-community/tomcat/webapps/OpenKM/WEB-INF/classes/extensions/macros.sql
/home/jc/openkm-6.3.0-community/tomcat/webapps/OpenKM/WEB-INF/classes/default.sql
/home/jc/openkm-6.3.0-community/tomcat/webapps/OpenKM/WEB-INF/classes/i18n/es-ES.sql
/home/jc/openkm-6.3.0-community/tomcat/webapps/OpenKM/WEB-INF/classes/i18n/en-GB.sql
/home/jc/openkm-6.3.0-community/tomcat/webapps/OpenKM/WEB-INF/classes/i18n/fr-FR.sql
/home/jc/encues2_basemaestra.sql
/home/jc/.cache/.fr-EfvDF1/encues2_cncdb.sql
/home/jc/.cache/.fr-oq1nqi/encues2_cncdb.sql
/home/jc/encues2_basemaestra-02-07-2014.sql
/home/jc/Descargas/prueba/encues2_cncdb.sql
/home/jc/Descargas/mysql_db.sql
/home/jc/Descargas/egm2014/contactos2010b.sql
/home/jc/Descargas/egm2014/backup/idm_2013Ola3.sql
/home/jc/Descargas/egm2014/egm.sql
/home/jc/Descargas/egm2014/scripts/cnc_db.sql
/home/jc/Descargas/encues2_SURCNC_Jun6.sql
/home/jc/Descargas/egm2014 (copia)/contactos2010b.sql
/home/jc/Descargas/egm2014 (copia)/egm.sql
/home/jc/Descargas/egm2014 (copia)/scripts/cnc_db.sql
